#!/usr/bin/env python3

import sys
import random

# define function

def factorizes_numbers(n):
    factor = []
    for i in range(2, int(n ** 0.5) + 1):
        while n % i == 0:
            factor.append(i)
            n //= i
    if n > 1:
        factor.append(n)
    return factor

# define function

def main(filena):
    with open(filena, 'r') as file:
        for line in file:
            numbers = int(line.strip())
            factor = factorizes_numbers(numbers)
            print(f"{numbers}={'*'.join(map(str, factor))}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    filena = sys.argv[1]
    main(filena)
